new = [1,2,2,3,2,4]
print(new.count(2))
print(new[:])
new.insert(1,15)
print(new)
new.remove(1)
print(new)
new.pop(3)
print(new)
new.clear()
print(new)
print(new.count(2))
print(new.reverse())
print(new.copy())
